### ISSUE TITLE
SendIQ or RTL-SDR command not working properly

### ISSUE THREAD

**Issue by Mifaxav** [F5OEO/rpitx#293]
recorded iq file using rtl sdr in 2 different frequencies. Sending it using sendiq makes me get the same output of a 0.3 second bump in the radio spectrum and gone. One of the frequencies had a car key fob recorded with the other being megahertz away. I have a Raspberry pi 3B+ and i truly dont know whats going on

**Comment by darksidelemm** [comment]
Interestingly I get similar results with sendiq and the transponder code. Platform is a RPI 3B+
Short carrier transmission, then nothing. 

I've tried quite a few variations, all with pretty similar results. I get transmission of a carrier for a while then nothing, or sometimes I just get nothing at all. 

I've also tried with a few other variations, to try and get somewhat more narrowband output:

* `rtl_fm -M raw -f 146500000 -s 96000 -F9 - | sudo ./sendiq -s 96000 -f 444000000 -t i16 -i /dev/stdin` - Short carrier on 444 MHz, then nothing.
* `rtl_fm -M raw -f 146500000 -s 96000 -F9 - | buffer | sudo ./sendiq -s 96000 -f 444000000 -t i16 -i /dev/stdin` - Same result as above.
* `cat /dev/urandom | sudo ./sendiq -s 96000 -f 444000000 -t i16 -i /dev/stdin` - This produces RF output at 444 MHz continuously.

This makes me think the issue is something to do with stdin input into sendiq, but there's not really anything obvious in the output that explains if this is the case or not. 

As a test I also tried:
```
rtl_fm -M raw -f 146500000 -s 96000 -F9 - > test.bin
```
(and waited a while, resulting in a ~16Mb file)

... then
```
cat test.bin | sudo ./sendiq -s 96000 -f 444000000 -t i16 -i /dev/stdin
```
... this resulting in a very short 'blip' at 444 MHz, then nothing. 

Running:
```
sudo ./sendiq -s 96000 -f 444000000 -t i16 -i test.bin
```
Results in the same effect, so maybe this rules out stdin issues, and instead there is just some issue with librpitx and/or sendiq on the platform I'm running?

As extra info:
* Raspbian Bullseye
* `uname -a` = Linux cameratest 6.1.25-v7+ #1647 SMP Wed Apr 26 17:35:40 BST 2023 armv7l GNU/Linux

**Comment by darksidelemm** [comment]
Similar behaviour on Raspbian Buster: Linux rpitx 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux

**Comment by Mifaxav** [comment]
i got the issue fixed by giving a higher samplerate. Try 960000 (not really a pro at this stuff lol)

**Comment by darksidelemm** [comment]
A higher samplerate doesnt really solve the issue for me! Also, given the example transponder code isn't working, that's probably something that should be looked into..

**Comment by Mifaxav** [comment]
then i have no idea what to do :( 

Good luck anyway... 

maybe try looking at how other people have done it and like get a better idea?
